/**
 * Real Mzizi programs and their real output, mirrored verbatim from
 * `mzizi-dev/mzizi` `main` at 4d0cdc3 (the third 8 October release, #104). The
 * examples the site shows are unchanged since be88017 (#91), the release these
 * outputs were first copied from; `records.mz` (C8) was added in #101, and its
 * output is the `.expected` file CI compares it with. Each output is what
 * `mz run` printed for that file on 2026-10-08, byte for byte the same as the
 * `.expected` file. Update them together, from a run, never by hand.
 */

export const PROGRAMS_COMMIT = "4d0cdc3";

export type Program = { path: string; source: string; output: string };

const program = (name: string, source: string, output: string): Program => ({
  path: `examples/${name}.mz`,
  source,
  output,
});

export const errorsProgram = program(
  "errors",
  '## Checks ages: one function fails with an error, its callers handle it with `match` or\n## propagate it with `try`, and `main` itself returns a result (RFC-0013 \u00a712).\nprogram errors\n\n  enum age_problem\n    negative say "is below zero"\n    too_old  say "is above 150"\n  end\n\n  fn main: result(none, age_problem)\n    print(describe(42))\n    print(describe(-3))\n    print(describe(200))\n    let total = try total_age(20, 22)\n    print("20 and 22 make {total}")\n    match total_age(20, 151)\n      case ok sum\n        print("20 and 151 make {sum}")\n      case error problem\n        print("20 and 151 were rejected: {problem} {problem.say}")\n    end\n  end fn main\n\n  fn check_age(n: int): result(int, age_problem)\n    when n < 0\n      return error(negative)\n    end\n    when n > 150\n      return error(too_old)\n    end\n    return n\n  end fn check_age\n\n  fn describe(n: int): text\n    match check_age(n)\n      case ok age\n        return "age {age} is fine"\n      case error problem\n        return "{n} is rejected: {problem} {problem.say}"\n    end\n  end fn describe\n\n  fn total_age(a: int, b: int): result(int, age_problem)\n    return try check_age(a) + try check_age(b)\n  end fn total_age\n\nend program errors\n',
  "age 42 is fine\n-3 is rejected: negative is below zero\n200 is rejected: too_old is above 150\n20 and 22 make 42\n20 and 151 were rejected: too_old is above 150\n",
);

export const numbersProgram = program(
  "numbers",
  '## Numbers, RFC-0013 \u00a74: `int` and `float`, never mixed without a conversion, integer\n## division that truncates, IEEE 754 floats that never trap, and \u00a73.8\'s text form.\n## `mz run examples/numbers.mz` prints what numbers.expected holds; CI compares the two.\nprogram numbers\n\n  fn main\n    let side = 3\n    let area = side * side\n    print("a square of side {side} has area {area}")\n    let radius = 1.5\n    let circle = pi() * radius * radius\n    print("a circle of radius {radius} has area {circle}")\n    print("rounded {circle.round()}, floor {circle.floor()}, ceil {circle.ceil()}, as an int {circle.to_int()}")\n    print("the mean of 7 and 2 is {mean(7, 2)}")\n    print("-7 / 2 is {-7 / 2}, -7 % 2 is {-7 % 2}, -7.0 / 2.0 is {-7.0 / 2.0}, 5.0 % 3.0 is {5.0 % 3.0}")\n    print("0.1 + 0.2 is {0.1 + 0.2}")\n    print("2 to the 62 is {2.pow(62)}, and 2.0 to the 10 is {2.0.pow(10)}")\n    print("the hypotenuse of 3 and 4 is {hypotenuse(3.0, 4.0)}")\n    print("big {1000000000000000000000.0}, small {0.00000015}, 1/3 {1.0 / 3.0}")\n    let missing = 0.0 / 0.0\n    print("1.0 / 0.0 is {1.0 / 0.0}, -1.0 / 0.0 is {-1.0 / 0.0}, 0.0 / 0.0 is {missing}")\n    print("nan is nan: {missing is missing}; is_nan: {missing.is_nan()}")\n    print("(-2.5).round() is {(-2.5).round()}, (-4).abs() is {(-4).abs()}, 2.5.min(1.5) is {2.5.min(1.5)}")\n    print((side > 2 and area < 10) or side is 0)\n  end fn main\n\n  fn pi: float\n    return 3.141592653589793\n  end fn pi\n\n  fn mean(a: int, b: int): float\n    return (a + b).to_float() / 2.0\n  end fn mean\n\n  fn hypotenuse(a: float, b: float): float\n    return (a * a + b * b).sqrt()\n  end fn hypotenuse\n\nend program numbers\n',
  "a square of side 3 has area 9\na circle of radius 1.5 has area 7.0685834705770345\nrounded 7.0, floor 7.0, ceil 8.0, as an int 7\nthe mean of 7 and 2 is 4.5\n-7 / 2 is -3, -7 % 2 is -1, -7.0 / 2.0 is -3.5, 5.0 % 3.0 is 2.0\n0.1 + 0.2 is 0.30000000000000004\n2 to the 62 is 4611686018427387904, and 2.0 to the 10 is 1024.0\nthe hypotenuse of 3 and 4 is 5.0\nbig 1.0e21, small 1.5e-7, 1/3 0.3333333333333333\n1.0 / 0.0 is inf, -1.0 / 0.0 is -inf, 0.0 / 0.0 is nan\nnan is nan: false; is_nan: true\n(-2.5).round() is -3.0, (-4).abs() is 4, 2.5.min(1.5) is 1.5\ntrue\n",
);

export const controlProgram = program(
  "control",
  '## Control flow in function bodies, RFC-0013 \u00a77 (C4): `else when`, `match` over an enum,\n## an int and a text, `when` and `match` used as values, `for each` over `range(a, to = b)`,\n## `while`, `break`, `continue` and early `return`.\n## `mz run examples/control.mz` prints what control.expected holds; CI compares the two.\nprogram control\n\n  enum shape\n    circle\n    square\n    triangle\n  end\n\n  fn main\n    for each n in range(1, to = 16)\n      print(fizzbuzz(n))\n    end\n    for each s in range(0, to = 3)\n      print("{pick(s)} has {corners(pick(s))} corners and is {kind(pick(s))}")\n    end\n    print("first multiple of 7 above 50 is {first_multiple(7, 50)}")\n    print("the odd numbers below 10 sum to {odd_sum(10)}")\n    print("collatz(27) takes {collatz(27)} steps")\n    print(day(6))\n    print(day(9))\n    print(greeting("fr"))\n    print(greeting("de"))\n  end fn main\n\n  fn fizzbuzz(n: int): text\n    when n % 15 is 0\n      return "FizzBuzz"\n    else when n % 3 is 0\n      return "Fizz"\n    else when n % 5 is 0\n      return "Buzz"\n    end\n    return "{n}"\n  end fn fizzbuzz\n\n  fn pick(i: int): shape\n    return match i\n      case 0\n        circle\n      case 1\n        square\n      else\n        triangle\n    end\n  end fn pick\n\n  fn corners(s: shape): int\n    match s\n      case circle\n        return 0\n      case square\n        return 4\n      case triangle\n        return 3\n    end\n  end fn corners\n\n  fn kind(s: shape): text\n    let label = when s is circle\n      "round"\n    else\n      "angular"\n    end\n    return label\n  end fn kind\n\n  fn first_multiple(of: int, above: int): int\n    var n = above + 1\n    while true\n      when n % of is 0\n        return n\n      end\n      n = n + 1\n    end\n  end fn first_multiple\n\n  fn odd_sum(limit: int): int\n    var total = 0\n    for each i in range(0, to = 100)\n      when i >= limit\n        break\n      end\n      when i % 2 is 0\n        continue\n      end\n      total = total + i\n    end\n    return total\n  end fn odd_sum\n\n  fn collatz(start: int): int\n    var n = start\n    var steps = 0\n    while n is not 1\n      n = match n % 2\n        case 0\n          n / 2\n        else\n          3 * n + 1\n      end\n      steps = steps + 1\n    end\n    return steps\n  end fn collatz\n\n  fn day(n: int): text\n    match n\n      case 6 7\n        return "{n} is a weekend day"\n      case 1 2 3 4 5\n        return "{n} is a weekday"\n      else\n        return "{n} is not a day of the week"\n    end\n  end fn day\n\n  fn greeting(lang: text): text\n    match lang\n      case "fr"\n        return "bonjour"\n      case "sw"\n        return "habari"\n      else\n        return "hello"\n    end\n  end fn greeting\n\nend program control\n',
  "1\n2\nFizz\n4\nBuzz\nFizz\n7\n8\nFizz\nBuzz\n11\nFizz\n13\n14\nFizzBuzz\ncircle has 0 corners and is round\nsquare has 4 corners and is angular\ntriangle has 3 corners and is angular\nfirst multiple of 7 above 50 is 56\nthe odd numbers below 10 sum to 25\ncollatz(27) takes 111 steps\n6 is a weekend day\n9 is not a day of the week\nbonjour\nhello\n",
);

export const recordsProgram = program(
  "records",
  '## Records, RFC-0013 §11 (C8): a record built by field name, copied with `with`, read by\n## field, given methods that read `self`, a field of a `var` assigned, and an `always`\n## clause that every value holds.\n## `mz run examples/records.mz` prints what records.expected holds; CI compares the two.\nprogram records\n\n  record point\n    field x: float\n    field y: float\n\n    fn norm: float\n      return (self.x * self.x + self.y * self.y).sqrt()\n    end fn norm\n\n    fn scaled(k: float): point\n      return point(x = self.x * k, y = self.y * k)\n    end fn scaled\n  end\n\n  record span\n    field low: int\n    field high: int\n\n    contract\n      always low <= high\n    end\n  end\n\n  fn width(s: span): int\n    return s.high - s.low\n  end fn width\n\n  fn main\n    let p = point(x = 3.0, y = 4.0)\n    print(p)\n    print(p.norm())\n    print(p.scaled(2.0))\n    print(p with (y = 0.0))\n    print(p is point(x = 3.0, y = 4.0))\n    var q = point(x = 1.0, y = 1.0)\n    q.x = 5.0\n    print(q)\n    let s = span(low = 2, high = 9)\n    print(width(s))\n    print("{s} is {width(s)} wide")\n  end fn main\n\nend program records\n',
  "point(x = 3.0, y = 4.0)\n5.0\npoint(x = 6.0, y = 8.0)\npoint(x = 3.0, y = 0.0)\ntrue\npoint(x = 5.0, y = 1.0)\n7\nspan(low = 2, high = 9) is 7 wide\n",
);
